version: 2
jobs:
  tigers:
    docker:
    - image: ubuntu:18.04
    steps:
    - checkout
    - run:
        name: "Install dependencies"
        command: ./installDeps.sh
    - run:
        name: "Update GIT submodules"
        command: git submodule update --init
    - run:
        name: "Build"
        command: ./build_tigers.sh

  erforce:
    docker:
    - image: ubuntu:18.04
    steps:
    - checkout
    - run:
        name: "Install dependencies"
        command: ./installDeps.sh
    - run:
        name: "Update GIT submodules"
        command: git submodule update --init
    - run:
        name: "Build"
        command: ./build_erforce.sh

workflows:
  version: 2
  main:
    jobs:
    - tigers:
        filters:
          tags:
            only: /.*/
    - erforce:
        filters:
          tags:
            only: /.*/

